classOrder = ["package-template"]
changelog = true
gitSourceBranch = "main"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = ""

[home]
enabled = true
includeReadme = false