name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

# This cookie is intentionally public, because secrets are not available in pull request CI runs
# It is from an empty account and not a security vulnerability
env:
  ROBLOSECURITY: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_83FF9A26525D9FDC782B5375A984B207FE53CA6C69D3B4A336265C58FB0D241C217A0A691749DB71F5913EECE0307EC0E4ED2E673046259FA684AA1EF0746F51769FAF2214759E7197428A57A2E3C8D742C3142320BD816E5260C40926E6A2E2F03CDA91528D2EB60E5E169DE659C62F714E0F7D6324D5D66AB9DFCB0AC62227136924340E0ACC4F1F524D4C83A7ADFE326B67822EB32D1FC05EA0178702ADC191BAC17FDFFA25A1FD5B0AE590F74FC441208D76BD1D34569EDE40F82C48B1602186DCACCDCD3BB0B1C2BCCC0A65B785620D1FF8CC7F5207E4394C147827EBDDA45B83772D90EB48BD0E2A2C8FA0AA2C33A1A98163CE6F46199C95CB3141C72C08F6B492A2F8610755C48C07BCB683DA565F4396FEADE378050F1999CEAD825FBD93CDF8C05DF78B1A0D764F8060F8BE5B5F7C8C809D10BDADC6C8F53E9296908C93B1F5751BFC547F260EA786A9965376F05B5485F8B3FFA8906566DBFF102976982E49582B6507E298D63797968ECCAFDBFC1A0C06A62427AFC4F7ED15D693379F22FC' }}

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wally-package-types
          version: "^1"

      - name: Download definition files & packages
        shell: bash
        run: |
          wally install
          cd definitions
          curl -O https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua
          curl -O https://gist.githubusercontent.com/zxibs/81fc195db5e0e374c63b98c262b99e1d/raw/utils.d.lua
          cd ..

      - name: Push new definition files
        shell: bash
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add definitions/ || echo 'No changes to add'
          git commit -m --amend --reset-author "Installed definitions" || echo 'No changes to commit'
          git push || echo 'No changes to push'

      - name: Analyze
        shell: bash
        run: |
          rojo sourcemap dev.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/
          luau-lsp analyze --no-strict-dm-types --ignore=Packages/** --base-luaurc=.luaurc --sourcemap=sourcemap.json \
            --definitions=definitions/globalTypes.d.lua \
            --definitions=definitions/utils.d.lua \
            --definitions=definitions/loaded.d.lua \
            --definitions=definitions/testez.d.lua \
            --definitions=definitions/remodel.d.lua \
            src/

  testing:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download dependencies
        shell: bash
        run: wally install

      - name: Build test place
        run: rojo build dev.project.json -o tests.rbxl

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        run: Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $((Resolve-Path .\\actions.ovpn).Path)"

      - name: Poll for IP Change
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq "78.142.193.246") {
                break
              }
            } catch {}
            if ($elapsed -ge 25) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ env.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ env.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        shell: bash
        run: run-in-roblox --place tests.rbxl --script TestRunner.server.lua > test-out.txt
        continue-on-error: true

      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'

      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
