name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wally-package-types
          version: "^1"

      - name: Download definition files & packages
        shell: bash
        run: |
          cd definitions
          curl -O https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua
          curl -O https://gist.githubusercontent.com/zxibs/81fc195db5e0e374c63b98c262b99e1d/raw/utils.d.lua
          cd ..

      - name: Push new definition files
        shell: bash
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add definitions/ || echo 'No changes to add'
          git commit -m --amend --reset-author "Installed definitions" || echo 'No changes to commit'
          git push || echo 'No changes to push'

      - name: Install packages
        shell: bash
        run: |
          wally install
          rojo sourcemap dev.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/
  
      - name: Analyze
        shell: bash
        run: |
          luau-lsp analyze --no-strict-dm-types src/ \
            --ignore=Packages/** --base-luaurc=.luaurc --sourcemap=sourcemap.json \
            --flag:LuauTinyControlFlowAnalysis=True \
            --flag:LuauLoopControlFlowAnalysis=True \
            --flag:LuauParseDeclareClassIndexer=True \
            --definitions=definitions/globalTypes.d.lua \
            --definitions=definitions/utils.d.lua \
            src/
