name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download definition files & packages
        shell: bash
        run: |
          cd definitions
          curl -O https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua
          curl -O https://gist.githubusercontent.com/zxibs/81fc195db5e0e374c63b98c262b99e1d/raw/utils.d.lua
          cd ..

      - name: Push new definition files
        shell: bash
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add definitions/ || echo 'No changes to add'
          git commit -m --amend --reset-author "Installed definitions" || echo 'No changes to commit'
          git push || echo 'No changes to push'

      - name: Analyze
        shell: bash
        run: |
          rojo sourcemap dev.project.json --output sourcemap.json
          luau-lsp analyze --no-strict-dm-types src/ \
            --ignore=Packages/** --base-luaurc=.luaurc --sourcemap=sourcemap.json \
            --flag:LuauParseDeclareClassIndexer=true \
            --definitions=definitions/globalTypes.d.lua \
            --definitions=definitions/utils.d.lua \
            --definitions=definitions/loaded.d.lua \
            --definitions=definitions/testez.d.lua \
            --definitions=definitions/remodel.d.lua \
            src/

  testing:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download dependencies
        shell: bash
        run: wally install

      - name: Build test place
        run: rojo build dev.project.json -o tests.rbxl

      - name: Download OpenVPN
        run: choco install openvpn

      - name: Run OpenVPN
        env:
          ovpn: ${{ secrets.OVPN }}
        run: |
          $ovpn | Out-File -FilePath "actions.ovpn"
          Start-Process -FilePath "C:\\Program Files\\OpenVPN\\bin\\openvpn.exe" -ArgumentList "--config $((Resolve-Path .\\actions.ovpn).Path)"

      - name: Poll for IP Change
        env:
          ip: ${{ secrets.IP }}
        run: |
          $elapsed = 0
          while ($true) {
            try {
              $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
              $content = ConvertFrom-Json $response.Content
              if ($content.origin -eq $ip) {
                break
              }
            } catch {}
            if ($elapsed -ge 25) {
              Write-Error "Timeout reached!"
              exit 1
            }
            Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
            Start-Sleep 5
            $elapsed += 5
          }
          Write-Output "Success!"

      - name: Validate Cookie
        run: |
          $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
          $cookie = New-Object System.Net.Cookie
          $cookie.Name = ".ROBLOSECURITY"
          $cookie.Value = "${{ secrets.ROBLOSECURITY }}"
          $cookie.Domain = ".roblox.com"
          $session.Cookies.Add($cookie);
          Invoke-WebRequest "https://avatar.roblox.com/v1/avatar" -WebSession $session -UseBasicParsing

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        shell: bash
        run: run-in-roblox --place tests.rbxl --script TestRunner.server.lua > test-out.txt
        continue-on-error: true

      - name: Screenshot
        if: failure()
        uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'desktop.jpg'

      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
