name: Deploy documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check for changed and added documentation files
        id: git-check
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git checkout "${GITHUB_REF:11}" --
          git add -AN
          echo "name=changed::$(if git diff-index --quiet HEAD~1 -- docs src; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Install node for installing moonwave
        if: steps.git-check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install moonwave
        if: steps.git-check.outputs.changed == 'true'
        run: npm i -g moonwave@latest
      
      - name: Deploy documentation
        if: steps.git-check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          moonwave build --publish
