name: Bump version and create changelog based on commits

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version for bumping ex: 1.0.0'
        required: true
        type: number

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repo history
        run: git fetch --prune --unshallow

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Bump version
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          sed -i 's/version.*/version = '"\"$VERSION\""'/' wally.toml
          sed -i "s/VERSION/$VERSION/" publish/wally.toml

      - name: Create changelog
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
          REPOSITORY: ${{ github.repository }}
        run: |
          cd publish
          lune create_changelog.lua $VERSION $REPOSITORY
          cd ..

      - name: Push changes
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add CHANGELOG.md wally.toml
          git commit -m "Bumped version to $VERSION and added a changelog for it"
          git push
