name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wally-package-types
          version: "^1"

      - name: Bump version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          sed -i 's/version.*/version = '"\"$VERSION\""'/' wally.toml
          sed -i "s/VERSION/$VERSION/" publish/wally.toml

      - name: Publish release to Wally
        shell: bash
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish

      - name: Build place file
        run: |
          wally install
          rojo sourcemap dev.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/
          rojo build publish.project.json -o package-template.rbxl

      - name: Create .rbxm file
        shell: bash
        run: |
          cd publish
          lune build.lua
          cd ..

      - name: Create release note
        shell: bash
        run: |
          cd publish
          lune get_changes.lua > CHANGES.md
          sed -i 's|rbxm|https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/package-template.rbxm|' RELEASE_NOTE.md
          sed -i 's|version|${{ github.ref_name }}|' RELEASE_NOTE.md
          cat CHANGES.md >> RELEASE_NOTE.md
          cd ..
      
      - name: Publish release to github
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ github.ref_name }}
          fail_on_unmatched_files: true
          body_path: publish/RELEASE_NOTE.md
          files: |
              publish/package-template.rbxm
